# Generated by Django 4.2.20 on 2025-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_studentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('send_sms', models.BooleanField(default=False)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
