# Generated by Django 5.2.1 on 2025-05-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_sentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not Delivered', 'Not Delivered')], default='Not Delivered', max_length=20),
        ),
    ]
