# Generated by Django 4.2.20 on 2025-05-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_sentmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmessage',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not Delivered', 'Not Delivered'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
